server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/guruguruzom/server-config.git
          default-label: master

###################location file##############################
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: file://${user.home}/path
#        git:
#          uri: https://github.com/guruguruzom/server-config.git


###################authentication security#####################
#git account info
#          username:
#          passwolrd:

#privary key regist
#            ignoreLocalSshSettings: true
#            private-key:
#              -----BEGIN RSA PRIVATE KEY-----
#              ....
#              -----END RSA PRIVATE KEY-----

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, busrefresh