server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/guruguruzom/server-config.git
#git account info
#          username:
#          passwolrd:

#privary key regist
#            ignoreLocalSshSettings: true
#            private-key:
#              -----BEGIN RSA PRIVATE KEY-----
#              ....
#              -----END RSA PRIVATE KEY-----