server:
  port: 8888

spring:
  application:
    name: config-service
    cloud:
      config:
        server:
          git:
            uri: https://github.com/guruguruzom/server-config.git

###################location file##############################
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: file://${user.home}/path
#        git:
#          uri: https://github.com/guruguruzom/server-config.git


###################authentication security#####################
#git account info
#          username:
#          passwolrd:

#privary key regist
#            ignoreLocalSshSettings: true
#            private-key:
#              -----BEGIN RSA PRIVATE KEY-----
#              ....
#              -----END RSA PRIVATE KEY-----