server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/guruguruzom/server-config.git
#privary ?? ? key ?? ? ??
#          uri: git@github.com:cheese10yun/blog-sample.git
#            ignoreLocalSshSettings: true
#            private-key:
#              -----BEGIN RSA PRIVATE KEY-----
#              ....
#              -----END RSA PRIVATE KEY-----